import { NbMenuItem } from "@nebular/theme";

export const MENU_ITEMS: NbMenuItem[] = [
  {
    title: "Dashboard",
    icon: "home-outline",
    link: "/pages/dashboard",
    home: true,
  },
  {
    title: "Master Data",
    icon: "folder-outline",
    children: [
      { title: "Pelanggan", link: "/pages/master/pelanggan" },
      { title: "Supplier", link: "/pages/master/supplier" },
      {
        title: "Produk / Barang & Jasa",
        children: [
          { title: "Daftar Produk", link: "/pages/master/produk" },
          { title: "Kategori Produk", link: "/pages/master/kategori-produk" },
          { title: "Satuan", link: "/pages/master/satuan" },
          // { title: "Harga Jual Produk", link: "/pages/master/harga-jual" },
        ],
      },
      {
        title: "Akun COA",
        children: [
          { title: "Struktur Akun", link: "/pages/master/coa" },
          { title: "Mapping Jurnal", link: "/pages/master/mapping-jurnal" },
        ],
      },
      { title: "Karyawan", link: "/pages/master/karyawan" },
      { title: "Gudang / Lokasi", link: "/pages/master/gudang" },
      // { title: "Divisi / Proyek", link: "/pages/master/divisi-proyek" },
      // { title: "Cabang", link: "/pages/master/branch" },
      // { title: "Mata Uang", link: "/pages/master/currency" },
      // { title: "Pajak", link: "/pages/master/pajak" },
    ],
  },
  {
    title: "Penjualan",
    icon: "shopping-cart-outline",
    children: [
      { title: "Penawaran", link: "/pages/menu/penjualan/penawaran" },
      { title: "Pesanan", link: "/pages/menu/penjualan/sales-order" },
      { title: "Pengiriman", link: "/pages/sales/delivery" },
      { title: "Faktur", link: "/pages/sales/invoice" },
      { title: "Pembayaran", link: "/pages/sales/payment" },
      { title: "Retur", link: "/pages/sales/return" },
      { title: "Piutang", link: "/pages/sales/receivable" },
      { title: "Laporan", link: "/pages/sales/report" },
    ],
  },
  {
    title: "Pembelian",
    icon: "car-outline",
    children: [
      { title: "Permintaan Pembelian", link: "/pages/purchase/pr" },
      { title: "Purchase Order", link: "/pages/purchase/po" },
      { title: "Penerimaan Barang", link: "/pages/purchase/receive" },
      { title: "Faktur Pembelian", link: "/pages/purchase/invoice" },
      { title: "Pembayaran", link: "/pages/purchase/payment" },
      { title: "Retur Pembelian", link: "/pages/purchase/return" },
      { title: "Hutang Usaha", link: "/pages/purchase/payable" },
      { title: "Laporan", link: "/pages/purchase/report" },
    ],
  },
  {
    title: "Persediaan",
    icon: "cube-outline",
    children: [
      { title: "Kartu Stok", link: "/pages/inventory/stock-card" },
      { title: "Stok Opname", link: "/pages/inventory/stock-opname" },
      { title: "Mutasi Gudang", link: "/pages/inventory/mutation" },
      { title: "Penyesuaian Stok", link: "/pages/inventory/adjustment" },
      {
        title: "Laporan Persediaan",
        children: [
          { title: "FIFO / Average", link: "/pages/inventory/fifo" },
          { title: "Nilai Persediaan", link: "/pages/inventory/value" },
        ],
      },
    ],
  },
  {
    title: "Produksi",
    icon: "settings-2-outline",
    children: [
      { title: "Bill of Material", link: "/pages/production/bom" },
      { title: "Work Order", link: "/pages/production/work-order" },
      { title: "Proses Produksi", link: "/pages/production/wip" },
      { title: "Hasil Produksi", link: "/pages/production/output" },
      { title: "Laporan Produksi", link: "/pages/production/report" },
    ],
  },
  {
    title: "Jasa / Service",
    icon: "briefcase-outline",
    children: [
      { title: "Daftar Layanan", link: "/pages/service/services" },
      { title: "Penjadwalan", link: "/pages/service/scheduling" },
      { title: "Invoice Layanan", link: "/pages/service/invoice" },
      { title: "Riwayat Layanan", link: "/pages/service/history" },
      { title: "Laporan Jasa", link: "/pages/service/report" },
    ],
  },
  {
    title: "Proyek / Kontrak",
    icon: "layers-outline",
    children: [
      { title: "Kontrak Proyek", link: "/pages/project/contract" },
      { title: "Anggaran (RAB)", link: "/pages/project/budget" },
      { title: "Realisasi", link: "/pages/project/realization" },
      { title: "Tagihan", link: "/pages/project/invoice" },
      { title: "Laporan Proyek", link: "/pages/project/report" },
    ],
  },
  {
    title: "Kas & Bank",
    icon: "credit-card-outline",
    children: [
      { title: "Kas Masuk", link: "/pages/cash/in" },
      { title: "Kas Keluar", link: "/pages/cash/out" },
      { title: "Mutasi Kas", link: "/pages/cash/transfer" },
      { title: "Rekonsiliasi Bank", link: "/pages/cash/reconcile" },
      { title: "Laporan Arus Kas", link: "/pages/cash/report" },
    ],
  },
  {
    title: "Akuntansi",
    icon: "book-outline",
    children: [
      { title: "Jurnal Umum", link: "/pages/accounting/journal" },
      { title: "Buku Besar", link: "/pages/accounting/ledger" },
      { title: "Neraca Saldo", link: "/pages/accounting/trial-balance" },
      {
        title: "Buku Pembantu",
        children: [
          { title: "Piutang", link: "/pages/accounting/subsidiary/receivable" },
          { title: "Hutang", link: "/pages/accounting/subsidiary/payable" },
          { title: "Bank", link: "/pages/accounting/subsidiary/bank" },
        ],
      },
      {
        title: "Laporan Keuangan",
        children: [
          { title: "Neraca", link: "/pages/accounting/balance-sheet" },
          { title: "Laba Rugi", link: "/pages/accounting/income-statement" },
          { title: "Perubahan Modal", link: "/pages/accounting/equity" },
          { title: "Arus Kas", link: "/pages/accounting/cashflow" },
        ],
      },
      { title: "Jurnal Penyesuaian", link: "/pages/accounting/adjustment" },
      { title: "Posting Transaksi", link: "/pages/accounting/posting" },
      { title: "Tutup Buku", link: "/pages/accounting/closing" },
      { title: "Audit & Pemeriksaan", link: "/pages/accounting/audit" },
    ],
  },
  {
    title: "Pajak",
    icon: "percent-outline",
    children: [
      { title: "Master Jenis Pajak", link: "/pages/tax/master" },
      { title: "Kode Pajak", link: "/pages/tax/code" },
      { title: "Faktur Pajak Keluaran", link: "/pages/tax/output-invoice" },
      { title: "Faktur Pajak Masukan", link: "/pages/tax/input-invoice" },
      { title: "PPh 21 (Karyawan)", link: "/pages/tax/pph21" },
      { title: "PPh 23 (Jasa / Royalti)", link: "/pages/tax/pph23" },
      { title: "e-Faktur / CSV Export", link: "/pages/tax/e-faktur" },
      { title: "e-Bupot Export", link: "/pages/tax/e-bupot" },
      { title: "Laporan Pajak", link: "/pages/tax/report" },
    ],
  },
  {
    title: "SDM & Payroll",
    icon: "people-outline",
    children: [
      { title: "Data Karyawan", link: "/pages/hr/employee" },
      { title: "Absensi", link: "/pages/hr/attendance" },
      { title: "Gaji & Tunjangan", link: "/pages/hr/salary" },
      { title: "Slip Gaji", link: "/pages/hr/payroll-slip" },
      { title: "BPJS & Potongan", link: "/pages/hr/bpjs" },
      { title: "Pajak PPh 21", link: "/pages/hr/tax" },
      { title: "Laporan Gaji", link: "/pages/hr/report" },
    ],
  },
  {
    title: "Aset Tetap",
    icon: "archive-outline",
    children: [
      { title: "Registrasi Aset", link: "/pages/asset/register" },
      { title: "Kategori Aset", link: "/pages/asset/category" },
      { title: "Penyusutan Otomatis", link: "/pages/asset/depreciation" },
      { title: "Mutasi / Disposisi", link: "/pages/asset/mutation" },
      { title: "Laporan Aset", link: "/pages/asset/report" },
    ],
  },
  {
    title: "Laporan & Analitik",
    icon: "bar-chart-outline",
    children: [
      { title: "Laporan Transaksi", link: "/pages/report/transaction" },
      { title: "Laporan Persediaan", link: "/pages/report/inventory" },
      { title: "Laporan Keuangan", link: "/pages/report/finance" },
      { title: "Laporan Produksi", link: "/pages/report/production" },
      { title: "Laporan Gaji", link: "/pages/report/salary" },
      { title: "Laporan Proyek", link: "/pages/report/project" },
      { title: "KPI Dashboard", link: "/pages/report/kpi" },
    ],
  },
  {
    title: "AI Assistant",
    icon: "bulb-outline",
    children: [
      { title: "Saran Pembelian", link: "/pages/ai/smart-purchase" },
      { title: "Saran Produksi", link: "/pages/ai/smart-production" },
      { title: "Forecast Penjualan", link: "/pages/ai/forecast-sales" },
      { title: "Forecast Stok", link: "/pages/ai/forecast-inventory" },
      { title: "Harga Optimal", link: "/pages/ai/smart-pricing" },
      { title: "Ringkasan Laporan", link: "/pages/ai/report-summary" },
      { title: "Chat AI (ERP Bot)", link: "/pages/ai/chat" },
    ],
  },
  {
    title: "Workflow & Approval",
    icon: "checkmark-circle-outline",
    children: [
      { title: "Approval Center", link: "/pages/approval/center" },
      { title: "Workflow Setup", link: "/pages/approval/setup" },
    ],
  },
  {
    title: "Helpdesk & Support",
    icon: "headphones-outline",
    children: [
      { title: "Tiket Bantuan", link: "/pages/support/ticket" },
      { title: "Basis Pengetahuan", link: "/pages/support/knowledge" },
      { title: "FAQ", link: "/pages/support/faq" },
    ],
  },
  {
    title: "Integrasi",
    icon: "link-outline",
    children: [
      { title: "Marketplace", link: "/pages/integration/marketplace" },
      { title: "POS System", link: "/pages/integration/pos" },
      { title: "API / WhatsApp", link: "/pages/integration/api" },
    ],
  },
  {
    title: "Manajemen Pengguna",
    icon: "lock-outline",
    children: [
      { title: "User", link: "/pages/security/user" },
      { title: "Role & Hak Akses", link: "/pages/security/role" },
      { title: "Audit Trail", link: "/pages/security/audit" },
    ],
  },
  {
    title: "Pengaturan",
    icon: "settings-outline",
    children: [
      { title: "Cabang Aktif", link: "/pages/settings/branch" },
      { title: "Periode Akuntansi", link: "/pages/settings/period" },
      { title: "Penomoran Transaksi", link: "/pages/settings/numbering" },
      { title: "Notifikasi & Email", link: "/pages/settings/notification" },
      { title: "Backup & Restore", link: "/pages/settings/backup" },
      { title: "Aktifkan Modul", link: "/pages/settings/module-mapping" },
      { title: "Mapping Menu", link: "/pages/settings/menu-mapping" },
    ],
  },
];
